//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.Agular.UserManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptService
    {
        public int ReceiptServiceId { get; set; }
        public int ReceiptId { get; set; }
        public string ServiceId { get; set; }
        public int OrderIndex { get; set; }
        public string ItemName { get; set; }
        public string Unit { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public System.DateTime DateCreate { get; set; }
    
        public virtual Service Service { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
