//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.Agular.UserManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receipt()
        {
            this.ReceiptServices = new HashSet<ReceiptService>();
        }
    
        public int ReceiptId { get; set; }
        public string ReceiptNumber { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> ReceiptTypeId { get; set; }
        public Nullable<int> ReceiptStatusId { get; set; }
        public string CustomerId { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public string TotalMoneyText { get; set; }
        public Nullable<System.DateTime> DateUpdate { get; set; }
        public string UserId { get; set; }
        public string ShopId { get; set; }
        public string GUID { get; set; }
        public string Description { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ReceiptStatu ReceiptStatu { get; set; }
        public virtual ReceiptType ReceiptType { get; set; }
        public virtual Shop Shop { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptService> ReceiptServices { get; set; }
    }
}
