//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH.Agular.UserManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.ReceiptServices = new HashSet<ReceiptService>();
        }
    
        public string ServiceId { get; set; }
        public string ServiceTypeId { get; set; }
        public int OrderIndex { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
        public string Alias { get; set; }
        public decimal ImportPrice { get; set; }
        public decimal Price { get; set; }
        public decimal DefaultQuantity { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public string ShopId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceiptService> ReceiptServices { get; set; }
        public virtual ServiceType ServiceType { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
